version: '3.8'

services:
  kamila-app:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_NEO4J_URI=bolt://neo4j:7687
      - QUARKUS_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - QUARKUS_NEO4J_AUTHENTICATION_PASSWORD=testtest
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testtest
    volumes:
      - neo4j-data:/data
volumes:
  neo4j-data:
